### ISSUE TITLE
Allow configuration of DLQ via props

### ISSUE THREAD

**Issue by reisingerf** [EYssel/sqs-dlq-monitoring#89]
Would it be possible to allow provisioning of DLQ properties similar to the main queue properties (or reuse props from the main queue)?

A simple use case: `enforceSSL` 
This can be set for the monitored queue via the `QueueProps`, but is not passed on to the DLQ. Only option at the moment is to create a DLQ outside of the construct and provide that, which sort of defeats its purpose / usefulness. 

Although the CDK defaults to `false`, from a security perspective enforcing SSL should perhaps even be the default.

Our use case can be found [here](https://github.com/umccr/orcabus/blob/f5b95259b7948fde07aabe53150726d49a5b117e/lib/workload/stateful/ica_event_pipe/component.ts#L33-L65).

**Comment by EYssel** [comment]
Hi @reisingerf,

Thanks for the feedback.

Am I correct in assuming that it would be useful if the following property is exposed as an optional way to customise your DLQ?:

```ts
{
   ...
   queueProps: QueueProps,
   dlqProps: QueueProps,
   ...
}
```

**Comment by reisingerf** [comment]
Yes, I think that would solve the issue.
